# Generated by Django 5.2.16 on 2026-09-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.RenameIndex(
            model_name='alert',
            new_name='core_alert_status_8c163b_idx',
            old_name='core_alert_status_6f6f6f_idx',
        ),
        migrations.RenameIndex(
            model_name='alert',
            new_name='core_alert_exam_se_ce407e_idx',
            old_name='core_alert_exam_se_7g7g7g_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='core_attend_exam_se_cd66fe_idx',
            old_name='core_attend_exam_se_5e5e5e_idx',
        ),
        migrations.RenameIndex(
            model_name='examsession',
            new_name='core_examse_exam_da_15e041_idx',
            old_name='core_examse_exam_da_3c3c3c_idx',
        ),
        migrations.RenameIndex(
            model_name='examstudentassignment',
            new_name='core_examst_exam_se_9469f7_idx',
            old_name='core_examst_exam_se_4d4d4d_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='core_studen_exam_pe_11ac61_idx',
            old_name='core_studen_exam_pe_1a1a1a_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='core_studen_roll_nu_9cbe47_idx',
            old_name='core_studen_roll_nu_2b2b2b_idx',
        ),
    ]
